// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddPriceController from "./add_price_controller"
application.register("add-price", AddPriceController)

import FormController from "./form_controller"
application.register("form", FormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import FileInputController from "./file_input_controller"
application.register("file-input", FileInputController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
